import "server-only";
import { randomUUID } from "node:crypto";
import { DEMO_PROFILE, DEMO_WORKSPACE_ID } from "./data";
import { demoPhase2Store } from "./phase2-store";
import type { Campaign, CampaignActivity, CampaignDetail, CampaignMessage, MessageVersion, OutreachChannel } from "@/features/campaigns/types";
import type { CampaignInput } from "@/features/campaigns/schemas";
import { scheduleMessages } from "@/features/campaigns/scheduling";

type Store = { campaigns: Map<string, Campaign[]>; messages: Map<string, CampaignMessage[]>; activity: Map<string, CampaignActivity[]>; claimed: Set<string>; audit: Array<{ action: string; entityId: string; at: string }>; usage: Map<string, { used: number; reserved: number; limit: number }> };
declare global { var __orliqoPhase3DemoStore: Store | undefined; }
const now = () => new Date().toISOString();
function version(message: Omit<CampaignMessage, "versions" | "attempts">, number = 1): MessageVersion { return { id: randomUUID(), number, subject: message.subject, body: message.body, sourceIds: message.sourceIds, facts: message.facts, riskFlags: [], unsupportedClaims: [], model: "orliqo-deterministic-fixture", promptVersion: "phase3-v1", createdAt: now() }; }
function seed(): Store {
  const campaign: Campaign = { id: "30000000-0000-4000-8000-000000000001", workspaceId: DEMO_WORKSPACE_ID, name: "Amman studios — website audit", description: "Grounded demo outreach for qualified studios.", goal: "free_audit", audienceSource: "saved", status: "running", targetProspectCount: 12, channels: ["email", "instagram"], mainOffer: "A concise website conversion audit", mainCta: "Reply to receive the audit", tone: "consultative", language: "English", personalizationDepth: "standard", followUpCount: 2, startAt: now(), sendingDays: [0,1,2,3,4,5,6], sendWindowStart: "09:00", sendWindowEnd: "17:00", timezone: "Asia/Amman", dailyLimit: 35, monthlyLimit: 700, minIntervalMinutes: 2, maxIntervalMinutes: 6, stopOnReply: true, autoReplenish: true, replenishThreshold: 4, replenishCount: 8, replenishMinimumScore: 70, replenishRequireApproval: true, createdAt: now(), updatedAt: now(), pausedAt: null, killedAt: null };
  const phase2 = demoPhase2Store();
  const leads = phase2.leads.get(DEMO_WORKSPACE_ID)!.filter((lead) => !lead.doNotContact && Boolean(phase2.detail.get(lead.id)?.sources[0])).slice(0, 8); const dates = scheduleMessages({ startAt: new Date(), count: leads.length, days: campaign.sendingDays, windowStart: campaign.sendWindowStart, windowEnd: campaign.sendWindowEnd, minInterval: 2, maxInterval: 6, dailyLimit: 35, seed: campaign.id });
  const messages = leads.map((lead, index) => { const sourceId = phase2.detail.get(lead.id)!.sources[0]!.id; const channel: OutreachChannel = index % 3 === 0 ? "instagram" : "email"; const base = { id: `40000000-0000-4000-8000-${String(index + 1).padStart(12,"0")}`, campaignId: campaign.id, leadId: lead.id, businessName: lead.businessName, channel, sequenceStep: 0, subject: channel === "email" ? `A practical idea for ${lead.businessName}` : null, body: `Hi ${lead.businessName} team — I noticed your public site shows a ${lead.websiteStatus.replaceAll("_", " ")} opportunity. We prepared a concise, no-obligation conversion audit grounded in your public website. Reply if you would like to see it.`, sourceIds: [sourceId], facts: [`Website status: ${lead.websiteStatus}`, `Business: ${lead.businessName}`], confidence: .92, approvalStatus: index < 5 ? "approved" as const : "needs_review" as const, sendStatus: index === 0 ? "sent" as const : index < 5 ? "scheduled" as const : "draft" as const, scheduledAt: dates[index]!.toISOString(), idempotencyKey: `${campaign.id}:${lead.id}:${channel}:0` }; return { ...base, versions: [version(base)], attempts: index === 0 ? [{ number: 1, result: "simulated_no_send", at: now() }] : [] }; });
  return { campaigns: new Map([[DEMO_WORKSPACE_ID, [campaign]]]), messages: new Map([[campaign.id, messages]]), activity: new Map([[campaign.id, [{ id: randomUUID(), summary: "Campaign launched in deterministic no-send demo mode", createdAt: now() }]]]), claimed: new Set(), audit: [], usage: new Map([[DEMO_WORKSPACE_ID, { used: 58, reserved: 4, limit: 700 }]]) };
}
export function demoPhase3Store(): Store { globalThis.__orliqoPhase3DemoStore ??= seed(); return globalThis.__orliqoPhase3DemoStore; }
export function campaignDetail(campaignId: string): CampaignDetail | null { const store = demoPhase3Store(); const campaign = [...store.campaigns.values()].flat().find((item) => item.id === campaignId); if (!campaign) return null; const usage = store.usage.get(campaign.workspaceId)!; const messages = store.messages.get(campaignId) ?? []; return { campaign: structuredClone(campaign), messages: structuredClone(messages), activity: structuredClone(store.activity.get(campaignId) ?? []), queueHealth: { ready: messages.filter((m) => ["scheduled","queued"].includes(m.sendStatus)).length, threshold: campaign.replenishThreshold, ...usage } }; }
export function createDemoCampaign(workspaceId: string, input: CampaignInput): Campaign { const item: Campaign = { id: randomUUID(), workspaceId, ...input, status: "draft", createdAt: now(), updatedAt: now(), pausedAt: null, killedAt: null }; const list = demoPhase3Store().campaigns.get(workspaceId) ?? []; list.unshift(item); demoPhase3Store().campaigns.set(workspaceId, list); demoPhase3Store().messages.set(item.id, []); demoPhase3Store().activity.set(item.id, [{ id: randomUUID(), summary: "Campaign draft created", createdAt: now() }]); return item; }
export function logDemoCampaign(campaignId: string, summary: string, action: string): void { const store = demoPhase3Store(); store.activity.get(campaignId)?.unshift({ id: randomUUID(), summary, createdAt: now() }); store.audit.push({ action, entityId: campaignId, at: now() }); }
export function generateDemoMessages(campaignId: string): number { const store = demoPhase3Store(); const campaign = [...store.campaigns.values()].flat().find((item) => item.id === campaignId); if (!campaign) return 0; const existing = store.messages.get(campaignId) ?? []; const leads = demoPhase2Store().leads.get(campaign.workspaceId)!.filter((lead) => !lead.doNotContact && lead.qualificationScore >= campaign.replenishMinimumScore).slice(0, campaign.targetProspectCount); for (const lead of leads) { const channel = campaign.channels[0] ?? "email"; const key = `${campaign.id}:${lead.id}:${channel}:0`; if (existing.some((message) => message.idempotencyKey === key)) continue; const source = demoPhase2Store().detail.get(lead.id)!.sources[0]!; const base = { id: randomUUID(), campaignId, leadId: lead.id, businessName: lead.businessName, channel, sequenceStep: 0, subject: channel === "email" ? `${campaign.mainOffer} for ${lead.businessName}` : null, body: `Hi ${lead.businessName} team — your public website indicates a ${lead.websiteStatus.replaceAll("_", " ")} opportunity. ${campaign.mainOffer}. ${campaign.mainCta}.`, sourceIds: [source.id], facts: [`Website status: ${lead.websiteStatus}`], confidence: .9, approvalStatus: "needs_review" as const, sendStatus: "draft" as const, scheduledAt: null, idempotencyKey: key }; existing.push({ ...base, versions: [version(base)], attempts: [] }); } store.messages.set(campaignId, existing); logDemoCampaign(campaignId, `${existing.length} grounded messages generated`, "campaign.messages_generated"); return existing.length; }
export const DEMO_ACTOR = DEMO_PROFILE.id;
