"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createCampaignAction } from "@/features/campaigns/actions";
import type { CampaignInput } from "@/features/campaigns/schemas";

const steps=["Goal","Audience","Discovery","Messaging","Schedule","Review"];
const initial: CampaignInput={ name:"Amman growth campaign",description:"",goal:"free_audit",audienceSource:"saved",targetProspectCount:8,channels:["email"],mainOffer:"A concise website conversion audit",mainCta:"Reply to receive the audit",tone:"consultative",language:"English",personalizationDepth:"standard",followUpCount:2,startAt:new Date(Date.now()+3600000).toISOString(),sendingDays:[1,2,3,4,5],sendWindowStart:"09:00",sendWindowEnd:"17:00",timezone:"Asia/Amman",dailyLimit:35,monthlyLimit:700,minIntervalMinutes:2,maxIntervalMinutes:6,stopOnReply:true,autoReplenish:false,replenishThreshold:4,replenishCount:8,replenishMinimumScore:70,replenishRequireApproval:true };
export function CampaignBuilder(){const [step,setStep]=useState(0);const [data,setData]=useState(initial);const [message,setMessage]=useState("");const [pending,start]=useTransition();const router=useRouter();const patch=<K extends keyof CampaignInput>(key:K,value:CampaignInput[K])=>setData((current)=>({...current,[key]:value}));const save=()=>start(async()=>{const result=await createCampaignAction(data);setMessage(result.message);if(result.ok&&result.id)router.push(`/app/campaigns/${result.id}`)});
return <div className="mx-auto max-w-5xl space-y-5"><div><p className="text-sm font-semibold text-primary">New campaign</p><h1 className="text-3xl font-bold">Build safe outreach</h1><p className="mt-1 text-sm text-muted-foreground">Grounded messages, human approval, deterministic no-send delivery.</p></div><ol className="grid grid-cols-3 gap-2 lg:grid-cols-6">{steps.map((label,index)=><li key={label} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${index===step?"border-primary bg-primary/10 text-primary":index<step?"bg-muted":"text-muted-foreground"}`}>{index<step?<Check className="mr-1 inline size-3"/>:null}{index+1}. {label}</li>)}</ol><section className="min-h-[390px] rounded-xl border bg-card p-5 sm:p-8">
{step===0?<div className="space-y-5"><h2 className="text-xl font-semibold">Campaign goal</h2><label className="grid gap-2 text-sm">Campaign name<Input value={data.name} onChange={(e)=>patch("name",e.target.value)}/></label><div className="grid gap-2 sm:grid-cols-3">{[["sell_service","Sell service"],["appointments","Generate appointments"],["free_audit","Free audit"],["promote_product","Promote product"],["partnership","Partnership"],["custom","Custom"]].map(([value,label])=><button key={value} onClick={()=>patch("goal",value as CampaignInput["goal"])} className={`rounded-lg border p-4 text-left text-sm font-semibold ${data.goal===value?"border-primary bg-primary/10":""}`}>{label}</button>)}</div></div>:null}
{step===1?<div className="space-y-5"><h2 className="text-xl font-semibold">Audience source</h2><div className="grid gap-3 sm:grid-cols-2">{[["saved","Saved ICP"],["custom","New audience"],["csv","CSV/XLSX import"],["ai_recommended","AI recommended"]].map(([value,label])=><button key={value} onClick={()=>patch("audienceSource",value as CampaignInput["audienceSource"])} className={`rounded-lg border p-5 text-left ${data.audienceSource===value?"border-primary bg-primary/10":""}`}><strong>{label}</strong><span className="mt-1 block text-xs text-muted-foreground">Suppression and duplicate checks always apply.</span></button>)}</div></div>:null}
{step===2?<div className="space-y-5"><h2 className="text-xl font-semibold">Discovery settings</h2><label className="grid gap-2 text-sm">Prospect count<Input type="number" value={data.targetProspectCount} onChange={(e)=>patch("targetProspectCount",Number(e.target.value))}/></label><label className="grid gap-2 text-sm">Minimum score<Input type="number" value={data.replenishMinimumScore} onChange={(e)=>patch("replenishMinimumScore",Number(e.target.value))}/></label><div className="grid gap-2 text-sm sm:grid-cols-2">{["Must have email","Exclude duplicates","Exclude previously contacted","Exclude suppressed"].map((item)=><label key={item} className="rounded-lg border p-3"><input type="checkbox" defaultChecked className="mr-2"/>{item}</label>)}</div></div>:null}
{step===3?<div className="space-y-5"><h2 className="text-xl font-semibold">Messaging strategy</h2><label className="grid gap-2 text-sm">Offer<Input value={data.mainOffer} onChange={(e)=>patch("mainOffer",e.target.value)}/></label><label className="grid gap-2 text-sm">Call to action<Input value={data.mainCta} onChange={(e)=>patch("mainCta",e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-2 text-sm">Tone<select className="h-9 rounded-lg border bg-background px-3" value={data.tone} onChange={(e)=>patch("tone",e.target.value as CampaignInput["tone"])}>{["professional","friendly","direct","consultative","luxury"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-sm">Language<Input value={data.language} onChange={(e)=>patch("language",e.target.value)}/></label><label className="grid gap-2 text-sm">Follow-ups<Input type="number" value={data.followUpCount} onChange={(e)=>patch("followUpCount",Number(e.target.value))}/></label></div><div className="rounded-lg border bg-muted/50 p-4 text-sm"><strong>Live deterministic sample</strong><p className="mt-2 text-muted-foreground">Hi [Business] team — your stored public evidence indicates [verified opportunity]. {data.mainOffer}. {data.mainCta}.</p></div></div>:null}
{step===4?<div className="space-y-5"><h2 className="text-xl font-semibold">Sending schedule</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-2 text-sm">Start<Input type="datetime-local" value={data.startAt.slice(0,16)} onChange={(e)=>patch("startAt",new Date(e.target.value).toISOString())}/></label><label className="grid gap-2 text-sm">Window start<Input type="time" value={data.sendWindowStart} onChange={(e)=>patch("sendWindowStart",e.target.value)}/></label><label className="grid gap-2 text-sm">Window end<Input type="time" value={data.sendWindowEnd} onChange={(e)=>patch("sendWindowEnd",e.target.value)}/></label><label className="grid gap-2 text-sm">Daily limit<Input type="number" value={data.dailyLimit} onChange={(e)=>patch("dailyLimit",Number(e.target.value))}/></label><label className="grid gap-2 text-sm">Min interval<Input type="number" value={data.minIntervalMinutes} onChange={(e)=>patch("minIntervalMinutes",Number(e.target.value))}/></label><label className="grid gap-2 text-sm">Max interval<Input type="number" value={data.maxIntervalMinutes} onChange={(e)=>patch("maxIntervalMinutes",Number(e.target.value))}/></label></div><p className="rounded-lg border bg-muted/50 p-3 text-sm text-muted-foreground">Default randomized interval is 2–6 minutes. Estimated finish: within {Math.ceil(data.targetProspectCount/data.dailyLimit)} sending day(s). Times render in {data.timezone}.</p></div>:null}
{step===5?<div className="space-y-5"><div className="flex items-center gap-3"><ShieldCheck className="size-8 text-primary"/><div><h2 className="text-xl font-semibold">Review and save</h2><p className="text-sm text-muted-foreground">Launch remains blocked until every message is grounded and approved.</p></div></div><dl className="grid gap-3 sm:grid-cols-2">{[["Goal",data.goal],["Audience",`${data.targetProspectCount} prospects`],["Offer",data.mainOffer],["Schedule",`${data.dailyLimit}/day · ${data.minIntervalMinutes}–${data.maxIntervalMinutes} min`],["Credits",`${data.targetProspectCount} reserved at launch`],["Safety","Suppression, duplicate, stop-on-reply, approval"]].map(([label,value])=><div key={label} className="rounded-lg border p-4"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>{message?<p role="status" className="text-sm">{message}</p>:null}</div>:null}</section><div className="flex justify-between"><Button variant="outline" disabled={step===0||pending} onClick={()=>setStep(s=>s-1)}><ArrowLeft/>Back</Button>{step<5?<Button onClick={()=>setStep(s=>s+1)}>Continue<ArrowRight/></Button>:<Button disabled={pending} onClick={save}>{pending?"Saving…":"Save campaign draft"}</Button>}</div></div>}
