allowBuilds:
  '@sentry/cli': true
  core-js: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
confirmModulesPurge: false
fetchTimeout: 600000
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
