"use server";
import { revalidatePath } from "next/cache";
import { requirePermission } from "@/features/permissions/server";
import { readDemoSession } from "@/features/auth/demo-session";
import { campaignInputSchema, type CampaignInput } from "./schemas";
import { createDemoCampaign, demoPhase3Store, generateDemoMessages, logDemoCampaign } from "@/features/demo/phase3-store";
import { demoPhase2Store } from "@/features/demo/phase2-store";
import { scheduleMessages } from "./scheduling";

export type CampaignActionResult = { ok: boolean; message: string; id?: string; fieldErrors?: Record<string,string[]> };
async function context(permission: "campaign:create"|"campaign:update"|"campaign:approve"|"campaign:launch"|"campaign:pause"|"campaign:kill"|"message:generate"|"message:edit"|"message:approve"|"message:send") { const value = await requirePermission(permission); if (!value) return null; const demo = (await readDemoSession())?.kind === "workspace"; return { value, demo }; }
export async function createCampaignAction(input: CampaignInput): Promise<CampaignActionResult> { const parsed = campaignInputSchema.safeParse(input); if (!parsed.success) return { ok:false, message:"Check the campaign fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const ctx = await context("campaign:create"); if (!ctx) return { ok:false, message:"You do not have permission to create campaigns." }; if (!ctx.demo) return { ok:false, message:"Connect a hosted Supabase project before creating non-demo campaigns." }; const item = createDemoCampaign(ctx.value.activeWorkspace.id, parsed.data); revalidatePath("/app/campaigns"); return { ok:true, id:item.id, message:"Campaign draft created." }; }
function locate(campaignId: string) { const store = demoPhase3Store(); const campaign = [...store.campaigns.values()].flat().find((item) => item.id === campaignId); return { store, campaign }; }
export async function generateCampaignMessagesAction(campaignId: string): Promise<CampaignActionResult> { const ctx = await context("message:generate"); if (!ctx?.demo) return { ok:false, message:"Message generation is available in demo mode until a provider is configured." }; const count = generateDemoMessages(campaignId); revalidatePath(`/app/campaigns/${campaignId}`); revalidatePath("/app/queue"); return { ok:true, message:`Generated ${count} grounded messages with stored source IDs.` }; }
export async function approveMessageAction(messageId: string): Promise<CampaignActionResult> { const ctx = await context("message:approve"); if (!ctx?.demo) return { ok:false, message:"Approval is unavailable." }; const message = [...demoPhase3Store().messages.values()].flat().find((item) => item.id === messageId); if (!message) return { ok:false, message:"Message not found." }; if (!message.sourceIds.length || message.versions.at(-1)?.unsupportedClaims.length) return { ok:false, message:"Resolve grounding warnings before approval." }; message.approvalStatus="approved"; logDemoCampaign(message.campaignId, `${message.businessName} message approved`, "message.approved"); revalidatePath(`/app/campaigns/${message.campaignId}`); revalidatePath("/app/queue"); return { ok:true, message:"Message approved." }; }
export async function rewriteMessageAction(messageId: string, mode: "shorten"|"friendly"|"translate"|"subject"): Promise<CampaignActionResult> { const ctx = await context("message:edit"); if (!ctx?.demo) return { ok:false, message:"Editing is unavailable." }; const message = [...demoPhase3Store().messages.values()].flat().find((item) => item.id === messageId); if (!message) return { ok:false, message:"Message not found." }; if (mode === "shorten") message.body = message.body.split(/(?<=[.!?])\s+/).slice(0,2).join(" "); if (mode === "friendly") message.body = `Hello! ${message.body.replace(/^Hi[^—]+—\s*/, "")}`; if (mode === "translate") message.body = `مرحباً فريق ${message.businessName} — هذه مسودة عربية تجريبية مبنية على المصدر العام المحفوظ. يرجى الرد للاطلاع على المراجعة.`; if (mode === "subject") message.subject = `A concise growth idea for ${message.businessName}`; const current = message.versions.at(-1)!; message.versions.push({ ...current, id: crypto.randomUUID(), number: current.number+1, subject:message.subject, body:message.body, createdAt:new Date().toISOString() }); message.approvalStatus="needs_review"; revalidatePath(`/app/campaigns/${message.campaignId}`); return { ok:true, message:"A new grounded version was saved for review." }; }
export async function controlCampaignAction(campaignId: string, action: "launch"|"pause"|"resume"|"kill"): Promise<CampaignActionResult> { const permission = action === "kill" ? "campaign:kill" : action === "launch" ? "campaign:launch" : "campaign:pause"; const ctx = await context(permission); if (!ctx?.demo) return { ok:false, message:"Campaign control is unavailable." }; const { store, campaign } = locate(campaignId); if (!campaign) return { ok:false, message:"Campaign not found." }; const messages=store.messages.get(campaignId) ?? []; if (action === "launch") { if (!messages.length || messages.some((m)=>m.approvalStatus!=="approved")) return { ok:false, message:"Approve every grounded message before launch." }; const leads=demoPhase2Store().leads.get(campaign.workspaceId) ?? []; if (messages.some((m)=>leads.find((l)=>l.id===m.leadId)?.doNotContact)) return { ok:false, message:"Suppressed leads must be removed before launch." }; const usage=store.usage.get(campaign.workspaceId)!; if (usage.used+usage.reserved+messages.length>usage.limit) return { ok:false, message:"Monthly usage limit would be exceeded." }; usage.reserved += messages.length; const times=scheduleMessages({ startAt:new Date(campaign.startAt), count:messages.length, days:campaign.sendingDays, windowStart:campaign.sendWindowStart, windowEnd:campaign.sendWindowEnd, minInterval:campaign.minIntervalMinutes, maxInterval:campaign.maxIntervalMinutes, dailyLimit:campaign.dailyLimit, seed:campaign.id }); messages.forEach((m,i)=>{m.sendStatus="scheduled";m.scheduledAt=times[i]!.toISOString()}); campaign.status="running"; }
  if (action==="pause") { campaign.status="paused"; campaign.pausedAt=new Date().toISOString(); messages.filter((m)=>["queued","scheduled"].includes(m.sendStatus)).forEach((m)=>m.sendStatus="paused"); }
  if (action==="resume") { campaign.status="running"; campaign.pausedAt=null; messages.filter((m)=>m.sendStatus==="paused").forEach((m)=>m.sendStatus="scheduled"); }
  if (action==="kill") { campaign.status="killed"; campaign.killedAt=new Date().toISOString(); messages.filter((m)=>!["sent","delivered","read","replied"].includes(m.sendStatus)).forEach((m)=>m.sendStatus="cancelled"); }
  campaign.updatedAt=new Date().toISOString(); logDemoCampaign(campaignId, `Campaign ${action} applied`, `campaign.${action}`); revalidatePath("/app/campaigns"); revalidatePath(`/app/campaigns/${campaignId}`); revalidatePath("/app/queue"); return { ok:true, message:`Campaign ${action} applied safely.` }; }
export async function dispatchDemoMessageAction(messageId: string): Promise<CampaignActionResult> { const ctx=await context("message:send"); if(!ctx?.demo)return{ok:false,message:"No live provider is configured."}; const store=demoPhase3Store(); const message=[...store.messages.values()].flat().find((m)=>m.id===messageId); if(!message)return{ok:false,message:"Message not found."}; const campaign=[...store.campaigns.values()].flat().find((c)=>c.id===message.campaignId); const lead=demoPhase2Store().leads.get(campaign!.workspaceId)?.find((l)=>l.id===message.leadId); if(!campaign||campaign.status!=="running"||message.approvalStatus!=="approved")return{ok:false,message:"Campaign and approval checks blocked dispatch."}; if(lead?.doNotContact){message.sendStatus="suppressed";return{ok:false,message:"Suppression blocked dispatch."}} if(store.claimed.has(message.idempotencyKey)||message.sendStatus==="sent")return{ok:true,message:"Duplicate dispatch ignored by idempotency key."}; store.claimed.add(message.idempotencyKey); message.sendStatus="sent"; message.attempts.push({number:message.attempts.length+1,result:"simulated_no_send",at:new Date().toISOString()}); const usage=store.usage.get(campaign.workspaceId)!; usage.reserved=Math.max(0,usage.reserved-1);usage.used+=1; logDemoCampaign(campaign.id, `${message.businessName}: deterministic no-send simulation completed`, "message.demo_sent"); revalidatePath("/app/queue"); return{ok:true,message:"Demo dispatch completed. No network send occurred."}; }
