import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { readDemoSession } from "@/features/auth/demo-session";
import { demoPhase3Store, campaignDetail } from "@/features/demo/phase3-store";
import { getWorkspaceContext } from "@/features/workspaces/data";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import type { Campaign, CampaignDetail } from "./types";

type CampaignRow = { id:string;workspace_id:string;name:string;description:string|null;goal:string;audience_source:string;status:Campaign["status"];target_prospect_count:number;main_offer:string|null;main_cta:string|null;tone:string|null;language:string;personalization_depth:string|null;follow_up_count:number;start_at:string|null;sending_days:number[];send_window_start:string;send_window_end:string;timezone:string;daily_limit:number;monthly_limit:number|null;min_interval_minutes:number;max_interval_minutes:number;stop_on_reply:boolean;auto_replenish:boolean;replenish_threshold:number;replenish_count:number;replenish_minimum_score:number;replenish_require_approval:boolean;created_at:string;updated_at:string;paused_at:string|null;killed_at:string|null };

export async function getCampaigns(): Promise<Campaign[]> { const session = await readDemoSession(); if (session?.kind === "workspace") return structuredClone(demoPhase3Store().campaigns.get(session.activeWorkspaceId) ?? []); const context = await getWorkspaceContext(); if (!context) return []; const supabase = await createServerSupabaseClient(); const { data } = await (supabase as unknown as SupabaseClient).from("campaigns").select("*").eq("workspace_id", context.activeWorkspace.id).order("updated_at", { ascending: false }); return ((data ?? []) as CampaignRow[]).map((row) => ({ id: row.id, workspaceId: row.workspace_id, name: row.name, description: row.description ?? "", goal: row.goal, audienceSource: row.audience_source, status: row.status, targetProspectCount: row.target_prospect_count, channels: [], mainOffer: row.main_offer ?? "", mainCta: row.main_cta ?? "", tone: row.tone ?? "professional", language: row.language, personalizationDepth: (row.personalization_depth ?? "standard") as Campaign["personalizationDepth"], followUpCount: row.follow_up_count, startAt: row.start_at ?? new Date().toISOString(), sendingDays: row.sending_days, sendWindowStart: row.send_window_start, sendWindowEnd: row.send_window_end, timezone: row.timezone, dailyLimit: row.daily_limit, monthlyLimit: row.monthly_limit ?? row.daily_limit * 20, minIntervalMinutes: row.min_interval_minutes, maxIntervalMinutes: row.max_interval_minutes, stopOnReply: row.stop_on_reply, autoReplenish: row.auto_replenish, replenishThreshold: row.replenish_threshold, replenishCount: row.replenish_count, replenishMinimumScore: row.replenish_minimum_score, replenishRequireApproval: row.replenish_require_approval, createdAt: row.created_at, updatedAt: row.updated_at, pausedAt: row.paused_at, killedAt: row.killed_at })); }
export async function getCampaignDetail(id: string): Promise<CampaignDetail | null> { const session = await readDemoSession(); if (session?.kind === "workspace") { const detail = campaignDetail(id); return detail?.campaign.workspaceId === session.activeWorkspaceId ? detail : null; } return null; }
